name: "Datapack Publisher"
author: "Boomber <boombercmd123@gmail.com>"
description: "Packing datapack and upload"
inputs:
  name:
    description: "Datapack name"
    required: false
  config:
    description: "Path to a config file for this action"
    required: true
  tag_name:
    description: "Tag name of the release"
    required: true
  body:
    description: "Release Body"
    required: false
  release_name:
    description: "Release Name"
    required: false
  commitish:
    description: "Commitish"
    required: false
  draft:
    description: "Is Draft Release?"
    required: false
  prerelease:
    description: "Is Pre-Release?"
    required: false
outputs:
  upload_url:
    description: "The url to the github release of this datapack"

runs:
  using: 'node12'
  main: 'dist/index.js'